### ISSUE TITLE
Trying to run example

### ISSUE THREAD

**Issue by cem2ran** [gleneivey/example-express-with-ghost-middleware#1]
Hi Glen,

I've followed all the instructions and I get the error below:

```
Test application is listening on port 2360
Ctrl+C to shut down
Migrations: Up to date at version 003
Possibly unhandled Error: No actions map found, please call permissions.init() before use.
    at CanThisResult.beginCheck (/Users/cem2ran/example-express-with-ghost-middleware/node_modules/ghost/core/server/permissions/index.js:155:15)
    at canThis (/Users/cem2ran/example-express-with-ghost-middleware/node_modules/ghost/core/server/permissions/index.js:205:19)
    at getSettingsResult (/Users/cem2ran/example-express-with-ghost-middleware/node_modules/ghost/core/server/api/settings.js:337:24)
    at Object.read (/Users/cem2ran/example-express-with-ghost-middleware/node_modules/ghost/core/server/api/settings.js:354:16)
    at initDbHashAndFirstRun (/Users/cem2ran/example-express-with-ghost-middleware/node_modules/ghost/core/server/index.js:49:25)
    at /Users/cem2ran/example-express-with-ghost-middleware/node_modules/ghost/core/server/index.js:167:13
From previous event:
    at Function.Promise$All [as all] (/Users/cem2ran/example-express-with-ghost-middleware/node_modules/ghost/node_modules/bluebird/js/main/promise.js:202:12)
    at ConfigManager.init (/Users/cem2ran/example-express-with-ghost-middleware/node_modules/ghost/core/server/config/index.js:65:20)
    at buildServer (/Users/cem2ran/example-express-with-ghost-middleware/node_modules/ghost/as-middleware.js:17:26)
    at Object.<anonymous> (/Users/cem2ran/example-express-with-ghost-middleware/index.js:41:13)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
```

**Comment by gleneivey** [comment]
Hi Cem,

Short version:  Very sorry to take this long to get back to you.  It's fixed now, but the easiest way to be sure you get the fix is to start over again from a clean repository.

Long version:  The bug was an interaction between the as-middleware changes on my branch and new Ghost features introduced in master after the last functional changes I'd made.  So the code broke when I rebased, but there were no unit tests to address the interaction, and the setup for the integration tests masked it.  (A condition I've fixed on my branch.)  Worse, it only happens/reproduces when Ghost is running the code it uses to setup a completely empty database, so all my initial attempts to reproduce from your report when nowhere until it occurred to me to start from scratch.

So, thanks very much for your note--it ended up being quite helpful to me, even though it's been so long you've almost certainly given up.  Apologies again.

As I said, the easiest way to get a working setup of the example is to start over.  If you want to go forward from your existing repository, you'll have to remove `content/ghost/data/*.db` (there's enough content here to prevent Ghost from re-initializing it, but not enough for you to actually run) and get a fresh copy of Ghost in `node_modules`.  I don't know if npm-install is smart enough to fetch updates to a module it's already downloaded.  My quick test says "no," but I might not have tried hard enough.  So, safest is to remove `node_modules/ghost` and then npm-install again.  If you do something else to update, you might want to double check the result.  If you have the task `setEnvForMiddlewareTests` defined in `Gruntfile.js`, then you're good to go.

Take care, and I'd love to hear from you if you get this working and it proves useful for you.
